### PR TITLE
Create initial CI workflow with GitHub Actions

### PR DESCRIPTION
**Pull request by EwoutH**
Builds with make and make check on Ubuntu on pushes and pull requests. GitHub Actions can be [enabled here](https://github.com/alcover/stricks/actions).

Fun note: This is probably the fastest running CI configuration I have ever written!

### CODE REVIEW

**Comment by alcover** [comment]
Thank you, you're my first ever pull request !
I'm still a git beginner so let me study a little what a pull (and GH actions) entail.
Sorry :)

**Comment by EwoutH** [comment]
Cool! I can explain a bit more about the GitHub Actions part.

GitHub Actions is a platform for _continuous integration_, the practice of automatically building, testing and sometimes doing other stuff when new code changes are proposed or merged.

My pull request (PR) adds a configuration file (called `ci.yml`, but could be named anything) in a specific folder (`.github/workflows`) for GitHub to let it know what it needs to run when. It doesn't change anything to your code, it just there to inform GitHub what needs to be done.

I this case, de configuration file starts with `on: [push, pull_request]`, which asks GitHub to run this workflow (the whole `ci.yml` thing) on each push to a branch and each PR. Then it goes on, telling GitHub there's one `job`, in this case called `build` (can be anything), which `runs-on` the `ubuntu-latest` platform, currently Ubuntu 20.04 Focal Fossa.

Then it lists the actual steps that need to be taken:

- `git clone` the repo, `cd` into it and checkout the right branch. This is all be done by [actions/checkout](https://github.com/actions/checkout).
- run the command `make`
- run the command `make check`

You can checkout the [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions) for specifics about what each element in the `ci.yml` file exactly does.

If all steps were completed successfully, it reports back with a nice green checkmark, so you know in this case `make` and `make check` can be run successfully! If you want to know more details, you can click the check mark and see exactly what GitHub Actiosn did and how it went ([example here](https://github.com/EwoutH/stricks/runs/2090779982)).

Screenshot_667

Of course this is quite a limited test currently, but it can be expanded at any point with any extra steps you like.

I hope this explains the GitHub Actions part a bit, if you have any other questions please let me know!

**Comment by alcover** [comment]
Heartfull thanks for the explanation, Ewout.

Next, we could add other targets on the road to make it portable.
Like C99, Windows, etc...

**Comment by EwoutH** [comment]
Awesome! Feel free to open an issue with all the platforms, targets and other things you would like to be tested in CI, and assign me to it. Then I will try to implement as much as possible (starting hopefully next week).

**Pull request merged**
